[package]
name = "lightgbm-example-binary-classification"
version = "0.1.0"
authors = ["vaaaaanquish <6syun9@gmail.com>"]
publish = false

[dependencies]
lightgbm = { path = "../../" }
csv = "1.1.5"
itertools = "0.9.0"
